/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "StripeTestLambda",
            "endpoint": "https://8bg6e3modk.execute-api.ap-northeast-1.amazonaws.com/dev",
            "region": "ap-northeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-northeast-1:9c3e080e-e0c9-46fc-b73d-ec23ff5e337d",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_Wux4GZIQF",
    "aws_user_pools_web_client_id": "5pohn6123nvh47cjmuivqt9864",
    "oauth": {}
};


export default awsmobile;
